server:
  context-path : /dd
  session-timeout: 1800
  port: 8101
logging:
  level:
    root: info
    com.core: debug
    com.server: debug
    HTTP_INVOKE_LOGGER: WARN
    DING_OPEN_CLIENT_SDK_LOGGER: WARN
spring:
  http:
    multipart:
      maxFileSize : 10Mb
      maxRequestSize : 100Mb
  thymeleaf:
    mode: LEGACYHTML5
    cache: false
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
  datasource:
    # 主数据源 OA
    primary:
      type: com.alibaba.druid.pool.DruidDataSource
      driverClassName: oracle.jdbc.OracleDriver
      url: jdbc:oracle:thin:oradba/ora123456@127.0.0.1:1521:aaa
      username: aaaa
      password: aaa
    # 辅数据源 云桥
    secondary:
      type: com.alibaba.druid.pool.DruidDataSource
      driverClassName: com.mysql.jdbc.Driver
      url: jdbc:mysql://127.0.0.1:1512/aaaa?useUnicode=true&characterEncoding=utf8&autoReconnect=true&useSSL=true
      username: aaaa
      password: aaaa
      #验证连接的有效性
      test-while-idle: true
      #获取连接时候验证，会影响性能
      test-on-borrow: true
      validation-query: SELECT 1
      #空闲连接回收的时间间隔，与test-while-idle一起使用，设置5分钟
      time-between-eviction-runs-millis: 300000
      #连接池空闲连接的有效时间 ，设置30分钟
      min-evictable-idle-time-millis: 1800000
    # 辅数据源 EXP
    thirdly:
      type: com.alibaba.druid.pool.DruidDataSource
      driverClassName: oracle.jdbc.driver.OracleDriver
      url: jdbc:oracle:thin:osap/osaptest@127.0.0.1:1521:test
      username: aaa
      password: aaa
      initialSize: 1
      minIdle: 10
      maxActive: 1000
      # 配置获取连接等待超时的时间
      maxWait: 120000
      # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      timeBetweenEvictionRunsMillis: 60000
      # 配置一个连接在池中最小生存的时间，单位是毫秒
      minEvictableIdleTimeMillis: 30000
      validationQuery: select 'x' FROM DUAL
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      # 打开PSCache，并且指定每个连接上PSCache的大小
      poolPreparedStatements: true
      maxPoolPreparedStatementPerConnectionSize: 200
      # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
      filters: stat,wall,slf4j
      # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
      connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
      # 合并多个DruidDataSource的监控数据
      #useGlobalDataSourceStat: true
    resources:
          static-locations: classpath:/,classpath:/static,classpath:/public,classpath:/resources,classpath:/META-INF/resources
    jpa:
          show-sql: true
          hibernate:
            ddl-auto: update
          properties:
            hibernate:
              dialect: org.hibernate.dialect.Oracle10gDialect
mybatis:
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: mybatis/**/*.xml
  typeAliasesPackage: com.server.pojo

#SAP测试机连接配置
jco :
  client :
    ashost : 127.0.0.11
    client : 0
    user : aaa
    passwd : aaa

#SAP正式机连接配置
#jco :
#  client :
#    ashost : 192.168.0.12
#    client : 800
#    user : abaprfc
#    passwd : xpp2@12

# 文件上传路径
dd:
#  正式机路径
  uploadPath: /var/uploaded_files/
  imagePath: file:///var/uploaded_files/dd/
#  测试机路径
#  uploadPath: D:/var/uploaded_files/
#  imagePath: file:///D:/var/uploaded_files/dd/
